name: Build Android APK for Python 3.7.5

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: artem-solopov/buildozer-action@v2
      with:
        work-dir: ./
        buildozer-version: stable

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: ./bin/*.apk
        retention-days: 30