name: Build Android APK for Python 3.7.5

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-8-jdk \
          python3-pip \
          autoconf \
          automake \
          build-essential \
          ccache \
          cmake \
          gettext \
          libffi-dev \
          libltdl-dev \
          libssl-dev \
          libtool \
          patch \
          pkg-config \
          python3-dev \
          zlib1g-dev \
          libncurses5-dev

    - name: Set Java 8 as default
      run: |
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
        sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.21
        pip install buildozer==1.2.0
        pip install virtualenv

    - name: Setup Android SDK and NDK
      run: |
        # 使用更简单的方法设置 Android 环境
        buildozer android debug 2>&1 | tail -20 || true

    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: videodownloader-apk
        path: bin/*.apk
        retention-days: 30

    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: .buildozer
        retention-days: 30